// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SportsScoresAPIDemo.Model;
using System;

namespace SportsScoresAPIDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171227121313_DbCreate")]
    partial class DbCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SportsScoresAPIDemo.Model.Entities.TeamEntity", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("CrestURL");

                    b.Property<string>("MarektValue");

                    b.Property<string>("Name");

                    b.Property<string>("ShortName");

                    b.HasKey("TeamId");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
